name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: List Secrest
        env:
          FASTLANE_ISSUER_ID: ${{secrets.FASTLANE_ISSUER_ID}}
        run: |
          import os
          KEY = os.getenv("FASTLANE_ISSUER_ID")
          for i in KEY:
            print(i)
          print('Next Key')
        shell: python
        
