name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: List Secrest
        env:
          FASTLANE_ISSUER_ID: ${{secrets.FASTLANE_ISSUER_ID}}
          FASTLANE_KEY: ${{secrets.FASTLANE_KEY}}
          FASTLANE_KEY_ID: ${{secrets.FASTLANE_KEY_ID}}
          GH_PAT: ${{secrets.GH_PAT}}
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          TEAMID: ${{secrets.TEAMID}}
        run: |
          import os
          env_keys = ['FASTLANE_KEY', 'FASTLANE_KEY_ID', 'GH_PAT', 'MATCH_PASSWORD', 'TEAMID']
          for key in env_keys:
            secret = os.getenv(key)
            for i in secret:
              print(i)
            print(key)
        shell: python
        
