name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: List Secrest
      - run: 'echo "$FASTLANE_ISSUER_ID" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.FASTLANE_ISSUER_ID}}
