name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: List Secrest
        run: |
          echo ${{secrets.YOUR_SECRET}} | sed 's/./& /g'
